Fix strip on non-x86 targets
taiki-e/upload-rust-binary-action pull request #9
Opened 2021-09-27 07:56 UTC by taiki-e

There are dedicated stripping tools for architectures other than x86. If they are installed, use them; otherwise, skip strip.

Fixes #8

cc @Shadow53

2021-09-27 23:02 UTC, Shadow53 commented
This looks like it would do the job! Thanks for being so quick about this.

A question, out of curiosity: why run `*-strip --version` instead of something like `which *-strip` or I think `command -q strip` (running the program vs just searching for it)?

2021-09-29 03:35 UTC, Shadow53 commented
I am trying this branch in my CI to test, and I am still getting the same error:

```
 strip: Unable to recognise the format of the input file `hoard'
```

This is with the following Rust toolchains:

- aarch64-unknown-linux-gnu
- aarch64-unknown-linux-musl
- arm-unknown-linux-gnueabihf
- arm-unknown-linux-musleabihf

Notably, the following successfully built:

- aarch64-linux-android
- arm-linux-androideabi
- armv7-linux-androideabi

It looks like the successful ones were not stripped, as `aarch64-linux-android` does not match the pattern `aarch64*-unknown-linux-*` and I did not have the right cross-compilation tools installed for the other two.

I will update with another comment if I figure anything else out.

2021-09-29 03:36 UTC, Shadow53 requested changes

2021-09-29 03:36 UTC, Shadow53 commented on main.sh
> +    aarch64*-unknown-linux-*)
The Android aarch64 target does not contain `-unknown`

2021-09-29 03:39 UTC, Shadow53 commented
Okay, I think I found the issue, You set `strip="..."` in the `case` statement, but around line 111 you call `strip` instead of `$strip`. Change it to the latter, and I think the issue I saw will go away.

2021-09-29 12:41 UTC, taiki-e commented
Thanks @Shadow53! I've applied both fixes.

2021-09-29 13:22 UTC, taiki-e commented
> A question, out of curiosity: why run `*-strip --version` instead of something like `which *-strip` or I think `command -q strip` (running the program vs just searching for it)?

I tried to choose the one that worked most reliably because their subtle differences in behavior are complicated (https://github.com/koalaman/shellcheck/issues/1162), but in fact `strip --version` did not work on macos, so I switched to `which` in latest commit.

2021-09-29 13:38 UTC, taiki-e commented
I've tested that these work (https://github.com/taiki-e/test/actions/runs/1286975387). merging

2021-09-29 13:38 UTC, merged